[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
prost = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
tonic-build = "0.11"
